### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#211]
https://app.getsentry.com/code-corps/code-corps-ember-staging/issues/135025619/

```
TypeError: Cannot read property 'get' of undefined
  at n.<anonymous> (/assets/code-corps-ember-cfd8b060d322d02c8af87fc2dce42649.js:4:27012)
  at n.find (/assets/vendor-904ee6b5c3c39501c2fb3c90c688c1c5.js:14:28487)
  at n.findUserSkill (/assets/code-corps-ember-cfd8b060d322d02c8af87fc2dce42649.js:4:26911)
  at n._selectSkill (/assets/code-corps-ember-cfd8b060d322d02c8af87fc2dce42649.js:2:13272)
  at n.keyDown (/assets/code-corps-ember-cfd8b060d322d02c8af87fc2dce42649.js:2:12048)
...
(12 additional frame(s) were not displayed)

TypeError: Cannot read property 'get' of undefined
```

**Comment by JoshSmith** [comment]
This is caused by `beforeModel` in the `projects-list` route when the user is not authenticated.

**Comment by JoshSmith** [comment]
Outdated. Will reopen if we see this recur on Sentry again.
