### ISSUE TITLE
Tests fail after cloning

### ISSUE THREAD

**Issue by stackptr** [code-corps/code-corps-ember#338]
Trying to get this project setup and running locally. I can run via `remote-deployment` but trying to run tests will fail:

```
➜  code-corps-ember git:(master) ember test
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
⠋ Buildingember-cli-sentry will not be loaded from bower installation
(node:65652) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
Built project successfully. Stored in "/Users/corey/Development/code-corps-ember/tmp/core_object-tests_dist-SQBp6pen.tmp".
not ok 1 PhantomJS 2.1 - Global error: SyntaxError: Functions cannot be declared in a nested block in strict mode at http://localhost:7357/assets/vendor-b0cb29b3bafe8d02a4741ea7c87e8017.js, line 58513
    ---
        Log: |
            { type: 'error',
              text: 'SyntaxError: Functions cannot be declared in a nested block in strict mode at http://localhost:7357/assets/vendor-b0cb29b3bafe8d02a4741ea7c87e8017.js, line 58513\n' }
    ...
not ok 2 PhantomJS 2.1 - Global error: Error: Could not find module ember-metal/core required by: ember-testing/index at http://localhost:7357/assets/test-support-fb63411330dc1fc96c77e45154906120.js, line 62
    ---
        Log: |
            { type: 'error',
              text: 'Error: Could not find module ember-metal/core required by: ember-testing/index at http://localhost:7357/assets/test-support-fb63411330dc1fc96c77e45154906120.js, line 62\n' }
    ...
not ok 3 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/code-corps-ember-eee1c17ae20dae8ac6475699c2355ec2.js, line 9
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/code-corps-ember-eee1c17ae20dae8ac6475699c2355ec2.js, line 9\n' }
    ...
not ok 4 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/tests-6715337fcee49d587ece7c23efe79e81.js, line 1
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/tests-6715337fcee49d587ece7c23efe79e81.js, line 1\n' }
    ...
not ok 5 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/test-loader-349ab1ab734112d855d75a327e14b006.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/test-loader-349ab1ab734112d855d75a327e14b006.js, line 3\n' }
    ...
not ok 6 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: EmberENV at http://localhost:7357/9422/tests/index.html?hidepassed, line 1062
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://localhost:7357/9422/tests/index.html?hidepassed, line 1062\n' }
    ...
```

Here are the versions of the dependencies I'm working with:

```
➜  code-corps-ember git:(master) node -v
v6.3.0
➜  code-corps-ember git:(master) bower -v
1.7.9
➜  code-corps-ember git:(master) ember -v
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
ember-cli: 2.6.2
node: 6.3.0
os: darwin x64
➜  code-corps-ember git:(master) phantomjs -v
2.1.1
```

I've installed node/phantomjs through Homebrew if that makes a difference. Thanks for any help

**Comment by thomascchen** [comment]
Not sure what's causing this, but it does looks like this is a node issue:
```
(node:65652) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```
Might be worth trying to fall back to an earlier version of node.

**Comment by stackptr** [comment]
Given that it seems this was symptomatic of bugs in node in prior releases (see https://github.com/nodejs/node-v0.x-archive/issues/5108) I can try rolling back. Is there a specific version I could target?

**Comment by thomascchen** [comment]
6.2.2. is working for me

**Comment by noslouch** [comment]
I can reproduce with the following system:
```
noSlouch@Slice ~/code-corps-ember
> $ node -v
v6.3.0

noSlouch@Slice ~/code-corps-ember
> $ bower -v
1.7.9

noSlouch@Slice ~/code-corps-ember
> $ ember -v
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/noSlouch/code-corps-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
ember-cli: 2.6.2
node: 6.3.0
os: darwin x64

noSlouch@Slice ~/code-corps-ember
> $ phantomjs -v
2.1.1
```
I'll roll back to 6.2.2 with these specs and report back.

**Comment by noslouch** [comment]
Still failing with `phantomjs` 2.1.1. I think it's a phantom thing.

**Comment by noslouch** [comment]
Yeah, this seems to be it: https://github.com/ariya/phantomjs/issues/14173

**Comment by WenInCode** [comment]
I was also running into this issue - can confirm rolling back to a `phantomjs@~1.9` worked for me.

**Comment by JoshSmith** [comment]
@stackptr can you verify if this rollback is indeed working for you?

**Comment by stackptr** [comment]
Unfortunately, I am running the macOS Sierra Beta 2 and as a consequence I cannot rollback on homebrew to `phantomjs@~1.9` due to upstream OS incompatibility. Removing it and installing via `npm` also results in errors during install (though it seems to complete) and then running `ember test` gives a different error:

```
➜  code-corps-ember git:(master) sudo npm install -g phantomjs@1.9    
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs/bin/phantomjs

> phantomjs@1.9.20 install /usr/local/lib/node_modules/phantomjs
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Error checking path, continuing { Error: Cannot find module '/usr/local/lib/node_modules/phantomjs/lib/location'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at getLocationInLibModuleIfMatching (/usr/local/lib/node_modules/phantomjs/install.js:332:19)
    at Promise._successFn (/usr/local/lib/node_modules/phantomjs/install.js:389:28)
    at nextTickCallback (/usr/local/lib/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'MODULE_NOT_FOUND' }
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /usr/local/lib/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [============================------------] 70%
Received 9187K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/phantomjs/lib/phantom
Copying extracted folder /usr/local/lib/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1469209156977/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs
/usr/local/lib
└─┬ phantomjs@1.9.20 
  ├─┬ extract-zip@1.5.0 
  │ ├─┬ concat-stream@1.5.0 
  │ │ ├── inherits@2.0.1 
  │ │ ├─┬ readable-stream@2.0.6 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@0.10.31 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── typedarray@0.0.6 
  │ ├── debug@0.7.4 
  │ ├─┬ mkdirp@0.5.0 
  │ │ └── minimist@0.0.8 
  │ └─┬ yauzl@2.4.1 
  │   └─┬ fd-slicer@1.0.1 
  │     └── pend@1.2.0 
  ├─┬ fs-extra@0.26.7 
  │ ├── graceful-fs@4.1.4 
  │ ├── jsonfile@2.3.1 
  │ ├── klaw@1.3.0 
  │ ├── path-is-absolute@1.0.0 
  │ └─┬ rimraf@2.5.4 
  │   └─┬ glob@7.0.5 
  │     ├── fs.realpath@1.0.0 
  │     ├─┬ inflight@1.0.5 
  │     │ └── wrappy@1.0.2 
  │     ├─┬ minimatch@3.0.2 
  │     │ └─┬ brace-expansion@1.1.6 
  │     │   ├── balanced-match@0.4.2 
  │     │   └── concat-map@0.0.1 
  │     └── once@1.3.3 
  ├─┬ hasha@2.2.0 
  │ ├── is-stream@1.1.0 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├── kew@0.7.0 
  ├── progress@1.1.8 
  ├─┬ request@2.67.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── bl@1.0.3 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@1.0.0-rc4 
  │ │ └── async@1.5.2 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.3 
  │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ └─┬ is-my-json-valid@2.13.1 
  │ │   ├── generate-function@2.0.0 
  │ │   ├─┬ generate-object-property@1.2.0 
  │ │   │ └── is-property@1.0.2 
  │ │   ├── jsonpointer@2.0.0 
  │ │   └── xtend@4.0.1 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.0 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.2 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.8.3 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├─┬ dashdash@1.14.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.13.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.11 
  │ │ └── mime-db@1.23.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@5.2.1 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.2.2 
  │ └── tunnel-agent@0.4.3 
  ├─┬ request-progress@2.0.1 
  │ └── throttleit@1.0.0 
  └─┬ which@1.2.10 
    └── isexe@1.1.2 

➜  code-corps-ember git:(master) phantomjs -v
➜  code-corps-ember git:(master) ember test
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
⠋ Buildingember-cli-sentry will not be loaded from bower installation
(node:87270) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
Built project successfully. Stored in "/Users/corey/Development/code-corps-ember/tmp/core_object-tests_dist-GqHNun3h.tmp".
not ok 1 Browser "phantomjs /Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/3370/tests/index.html?hidepassed" exited unexpectedly with exit code 0.

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/lib/app.js:394:15)
    at EventEmitter.App.exit (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/lib/app.js:155:23)
    at /Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/lib/app.js:149:14
    at tryCatcher (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/corey/Development/code-corps-ember/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

I retrieved earlier compiled versions from phantomjs.org but both 1.9.8 and 2.0.0 error out when trying to print the version.

**Comment by noslouch** [comment]
hm... try not using `sudo` to install. or else change the ownership on `/usr/local/lib/` to yourself so it can run w/o `sudo`. [Here for more.](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by JoshSmith** [comment]
Yes, agreed on avoiding `sudo` with `npm`. It causes all sorts of nastiness.

Out of curiosity, do you use `nvm`?

**Comment by stackptr** [comment]
I do not use `nvm` -- installing without sudo yields the same errors

**Comment by noslouch** [comment]
> I retrieved earlier compiled versions from phantomjs.org but both 1.9.8 and 2.0.0 error out when trying to print the version.

This sounds like a phantom issue. If you really want the tests for local development, you can try commenting out phantom in your local `testem.js` file in the `"launch_in_dev"` section, so:
```
  "launch_in_dev": [
    // "PhantomJS",
    "Chrome"
  ]
```
should at least avoid your phantom issues.

**Comment by thomascchen** [comment]
@stackptr You might also want to `nombom` after doing the uninstalling phantomjs via homebrew and reinstalling via npm:

```
npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install
```

**Comment by JoshSmith** [comment]
@stackptr and @thomascchen there's also `nombom` on `npm`: https://www.npmjs.com/package/nombom

**Comment by stackptr** [comment]
An afternoon of clearing caches, uninstalling phantomjs, resetting the repo, avoiding sudo, and so forth has yielded few results. I have found out that the latest versions of phantomjs all seem to print a version of `2.1.1` and that installing it via `phantomjs-prebuilt` removes the weird callback where it complains about `Error: Cannot find module '/usr/local/lib/node_modules/phantomjs/lib/location'`

Installing 1.9 is the closest I can get to having the headless tests working, console output above remains unchanged.

However, there is a tenable solution by building and hitting `/tests` where all tests pass. It seems like this is an issue better left for the phantomjs devs

**Comment by JoshSmith** [comment]
>  It seems like this is an issue better left for the phantomjs devs

@stackptr I'm inclined to agree on this point, though hate that I couldn't solve your issue here. Do you want to close this in that case? People can at least still find it, even if it's not open.

**Comment by stackptr** [comment]
Sure thing
