### ISSUE TITLE
Running tests in phantomjs on a fresly cloned repo fails

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#618]
# Problem

As stated in the title, a fresly cloned repo fails to run tests using either `ember t` (circumvents ember-exam) or `ember-exam` fails with synthax errors

```
Your branch is up-to-date with 'origin/develop'.
Nikolas-MacBook-Pro:code-corps-ember begedin$ ember exam
Built project successfully. Stored in "/Users/begedin/git/code-corps-ember/tmp/core_object-tests_dist-jwWW4W2V.tmp".
not ok 1 PhantomJS 2.1 - Global error: SyntaxError: Expected token '}' at http://localhost:7357/assets/vendor-47e489fa5e003edd778e03208ce1c0bb.js, line 57128
    ---
        Log: |
            { type: 'error',
              text: 'SyntaxError: Expected token \'}\' at http://localhost:7357/assets/vendor-47e489fa5e003edd778e03208ce1c0bb.js, line 57128\n' }
    ...
not ok 2 PhantomJS 2.1 - Global error: Error: Could not find module ember-metal/core required by: ember-testing/index at http://localhost:7357/assets/test-support-7f8c06eb011cd2da8702a3dd1ce98c58.js, line 62
    ---
        Log: |
            { type: 'error',
              text: 'Error: Could not find module ember-metal/core required by: ember-testing/index at http://localhost:7357/assets/test-support-7f8c06eb011cd2da8702a3dd1ce98c58.js, line 62\n' }
    ...
not ok 3 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/code-corps-ember-89124b1c862915d58eb4ac50c95d1d34.js, line 9
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/code-corps-ember-89124b1c862915d58eb4ac50c95d1d34.js, line 9\n' }
    ...
not ok 4 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/tests-c7927ed0fe8e84e6b3b83ad325549fb1.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/tests-c7927ed0fe8e84e6b3b83ad325549fb1.js, line 3\n' }
    ...
not ok 5 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: EmberENV at http://localhost:7357/9317/tests/index.html?hidepassed, line 1061
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://localhost:7357/9317/tests/index.html?hidepassed, line 1061\n' }
    ...

```

This only seems to be happening locally. CI tests run just fine. Since CI uses Phantomjs 1.9, I tried installing that instead, but with no luck.

```
Built project successfully. Stored in "/Users/begedin/git/code-corps-ember/tmp/core_object-tests_dist-OKycnTbc.tmp".
not ok 1 Browser "phantomjs /Users/begedin/git/code-corps-ember/node_modules/testem/assets/phantom.js http://localhost:7357/4961/tests/index.html?hidepassed" failed to connect. testem.js not loaded?

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (/Users/begedin/git/code-corps-ember/node_modules/testem/lib/app.js:434:15)
    at EventEmitter.App.exit (/Users/begedin/git/code-corps-ember/node_modules/testem/lib/app.js:189:23)
    at /Users/begedin/git/code-corps-ember/node_modules/testem/lib/app.js:103:14
    at tryCatcher (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/begedin/git/code-corps-ember/node_modules/testem/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:516:17)
```

My assumption here is that the error is the same, it's just that a newer PhantomJS is able to provide more useful information.

**Comment by begedin** [comment]
More info. PhantomJS tests, in extremely rare cases, actually manage to run without issues, so it must be some sort of build order/ caching issue. I'm trying to figure out a pattern.

**Comment by JoshSmith** [comment]
I just cloned myself and everything worked fine.

```
ember-cli: 2.8.0
node: 4.2.4
os: darwin x64
phantomjs: 1.9.7
npm: 2.14.12
nvm: 0.20.0
```

Can you give me your versions for the above?

**Comment by begedin** [comment]
```
ember-cli: 2.8.0
node: 5.9.0
os: darwin x64
phantomjs: 2.1.1
npm: 3.7.3
nvm: 0.32.0
```

2.1.1 is the earliest available PhantomJS version available in `npm view phantomjs-prebuilt versions`. Installing the older obsolete `phantomjs` npm package doesn't work at all (install passes, executable is added to path, but doesn't respond at all.

Homebrew has 1.9.2 and 1.9.8 available, but neither will install because they fail on anything `Yosemite` or newer (I'm on `Sierra`).

Downloading the 1.9.7 package and installing manually gives me a `Segmentation fault: 11` when trying to run it.

Installing all the other packages to those specific versions, but leaving phantomjs doesn't help.

I'm thinking it's probably a Sierra issue of some sort. Googling tells me 1.9.x fails on sierra, so it's not an option to downgrade.

I will say that the tests pass more often if I run them alongside chrome tests, somehow. It seems like there's some sort of race condition somewhere, causing the browser to run before the build i fully done. I'm not really sure what's going on.

Right now, it seems like the best hope is that there will be an update which will make it work again.

**Comment by JoshSmith** [comment]
@begedin is this still failing?

**Comment by begedin** [comment]
Yes, it is, but as far as I can tell, it's purely sierra related. I'll try and pull fresh tool versions during the weekend, to see if something was resolved.

It does fail let's often when running tests in phantom and chrome at the same time.
